### ISSUE TITLE
Delete a line,  and press p

### ISSUE THREAD

**Issue by Jb00** [stefanoborini/vai#162] opened 2015-01-05 14:50 UTC
Hi, 

When I do the following :

delete a line with dd
then press p,  it crash with below issue.

Apologies. Vai has crashed.
---------------------------
Traceback (most recent call last):
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/__init__.py", line 142, in main
    app.exec_()
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vaitk/gui/VApplication.py", line 114, in exec_
    self.processEvents(True)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vaitk/gui/VApplication.py", line 121, in processEvents
    self._processKeyEvents()
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vaitk/gui/VApplication.py", line 239, in _processKeyEvents
    self._processSingleKeyEvent(event)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vaitk/gui/VApplication.py", line 262, in _processSingleKeyEvent
    widget.keyEvent(key_event)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/EditArea.py", line 112, in keyEvent
    self._controller.handleKeyEvent(event)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/controllers/EditAreaController.py", line 435, in handleKeyEvent
    new_state = state.handleEvent(event, self._buffer, self._global_state, self._edit_area, self._editor_controller)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/controllers/EditAreaController.py", line 169, in handleEvent
    result = command.execute()
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/models/commands/InsertLineAfterCommand.py", line 19, in execute
    document.insertLine(pos[0]+1, self._text)
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/models/TextDocument.py", line 246, in insertLine
    self._contents.insert(line_index, [char_meta, _withEOL(text)])
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/models/TextDocument.py", line 674, in _withEOL
    return text+EOL
TypeError: can only concatenate tuple (not "str") to tuple

Your buffers have been dumped to the following files

  <...>vaidump-step.py-93870.txt
  <...>vaidump-executor.py-73136.txt

The traceback has been saved in vai_crashreport.out

**Comment by stefanoborini** [comment] 2015-01-05 17:21
I think it's fixed in 1.5, let me check

**Comment by stefanoborini** [comment] 2015-01-05 17:22
Confirmed still present.

**Comment by Jb00** [comment] 2015-01-05 17:59
Hi, 

Thanks, 

I don't have your email so I couldn't ask at another place,  but I've been using vai a bit this morning for work,  and I found some issues(4 so far). Do you want me to raise them all, or send you an email explaining them ? 

Thanks

**Comment by stefanoborini** [comment] 2015-01-05 18:19
If they are bugs, post them all. I am fixing this one this evening. It's trivial, but it's a problem arising from an old design I am slowly outdating and of course I missed a spot. I will fix it quickly now, but for 1.6 I will clean it up because I don't like leaky stuff.

If they are a longer issue/request/discussion, you can send me a mail. stefano.borini at gmail

**Closed** 2015-01-05 21:46 UTC
Labels: Bug
